name: bin_day_brain
description: "Wollongong Smart Bin Reminders - Never miss bin day again!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "bin-day-brain-icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "bin-day-brain-icon.png"

flutter:
  uses-material-design: true
